spring.application.name=Fast-and-Furious-Food
spring.datasource.url=jdbc:h2:mem:fastfuriousdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=erf
spring.datasource.password=2diSenai
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true